project:
  type: website
  output-dir: docs

website:
  title: "Wildfires and Watersheds"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: timeline.qmd
      - href: synthesis.qmd
      - href: AI-synthesis.qmd
      - href: eda_text.qmd
        text: Analysis
      - href: networks.qmd
      - href: about.qmd
        text: Community
comments:
  giscus: 
    repo: Burning-Issues-Watersheds/5-bui-user.interface

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true



