---
title: "Knowledge Networks"
editor: visual
---
# Our initial survey

We have got responses from 67 wildfire scientists to the following questions:

-   In your opinion, which are 2 of the most **pressing questions** that need to be addressed to further our understanding of wildfire impacts on biogeochemical cycling in watersheds.
-   What are the most important **pathways** towards better integrating fire science across scientific disciplines?
-   What are the key **roadblocks** towards a more holistic understanding of the cumulative spatiotemporal impacts of wildfires in terrestrial and aquatic environments across both short and long timescales?

### Text Analysis Networks

Text analysis of survey responses is here. You can zoom and move the network around!

#### Pressing questions

```{=html}
<iframe src="../3-bui-production.hub/pressing_questions_answers_interactive.html" width="100%" height="600px" loading = "lazy"></iframe>
```
#### Roadblocks

```{=html}
<iframe src="../3-bui-production.hub/roadblocks_answers_interactive.html" width="100%" height="600px" loading = "lazy"></iframe>
```
#### Pathways

```{=html}
<iframe src="../3-bui-production.hub/pathways_answers_interactive.html" width="100%" height="600px"> loading = "lazy"</iframe>
```


### Literature network

Text analysis of abstracts from references cites in survey responses is here. You can zoom and move the network around!

#### Pressing questions

```{=html}
<iframe src="../3-bui-production.hub/pressing_questions_abstract_interactive.html" width="100%" height="600px" loading = "lazy"></iframe>
```
#### Roadblocks

```{=html}
<iframe src="../3-bui-production.hub/roadblocks_abstract_interactive.html" width="100%" height="600px" loading = "lazy"></iframe>
```
#### Pathways

```{=html}
<iframe src="../3-bui-production.hub/pathways_abstract_interactive.html" width="100%" height="600px"> loading = "lazy"</iframe>
```





### [Feedback Prompt](https://github.com/Burning-Issues-Watersheds/5-bui-user.interface/discussions/6)

#### Take a look at the word cloud networks & respond in the comment box in the link above!

These have been created based on your responses to the survey questions. There is a word cloud for: 1) the pressing questions 2) the roadblocks and 3) the pathways for wildfires and watershed science.

1.  🔥 What connections jump out for the burning issues? (10 words or less per "burning issue")
2.  🔥 What connections do you see for roadblocks? (10 words or less per roadblock)
3.  🔥 What connections do you see for pathways? (10 words or less per pathway)
4.  🔥 What connections do you see across the questions? i.e. which pathways could address which roadblocks? Which burning issues could be addressed by which pathways, etc?
